package resistorcontrollerIml

import "github.com/shpakunya/pkg/components"

// TODO Добавить обозначенияы
func (ResistorController) GenerateMaterial(SquareResistance, PermissibleSpecificPowerDissipation, TemperatureCoefficientOfResistance, Senescence float64) components.ResistorMaterial {
	return components.ResistorMaterial{
		Name: "Custom",
		SquareResistance: components.Parameter{Name: "Квадратное сопротивление", Symbol: "ρкв",
			Unit: "Ом/кв", Value: SquareResistance},
		PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
			Unit: "Вт/см^2", Value: PermissibleSpecificPowerDissipation},
		TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
			Unit: "1/град * 10^-4", Value: TemperatureCoefficientOfResistance},
		Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
			Unit: "(1 Вт/см^2 при 85 °C), %", Value: Senescence},
	}
}

func (ResistorController) GetMaterials() []components.ResistorMaterial {
	return []components.ResistorMaterial{
		{
			Name: "Кермет К50-С", // 0
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 10000.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 2.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 1.0},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 0},
		},
		{
			Name: "Хром", // 0
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 500.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 1.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 2.0},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 0},
		},
		{
			Name: "Тантал", // 0
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 100.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 3.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: -2.0},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 0},
		},
		{
			Name: "Нихром", // 0
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 300.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 2.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 2.5},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 0},
		},
		{
			Name: "Сплав МЛТ3-М",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 500.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 2.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 2.4},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 0.5},
		},
		{
			Name: "Кермет К-20С",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 3000.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 2.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 0.5},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 0},
		},
		{
			Name: "Сплав 1004",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 50000.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 5.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 15.0},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 2.0},
		},
		{
			Name: "Сплав 1714",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 500.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 5.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 2.0},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 1.0},
		},
		{
			Name: "Сплав 2005",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 500000.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 5.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 12.0},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 2.0},
		},
		{
			Name: "Сплав 2310",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 50000.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 5.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 12.0},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 2.0},
		},
		{
			Name: "Сплав 3001",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 3000.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 5.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 1.0},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 0.5},
		},
		{
			Name: "Сплав 3710",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 3000.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 5.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 1.0},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 0.5},
		},
		{
			Name: "Сплав 4206",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 1000.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 2.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 0.5},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 0.5},
		},
		{
			Name: "Сплав 4400",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 5000.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 10.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 3},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 0},
		},
		{
			Name: "Сплав 4800",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 1000.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 5.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 2},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 1},
		},
		{
			Name: "Сплав 5006",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 20.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 5.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 0.5},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 2},
		},
		{
			Name: "Сплав 5402",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 100.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 2.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 0.5},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 1},
		},
		{
			Name: "Сплав 5406 К",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 500.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 2.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 0.5},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 1},
		},
		{
			Name: "Сплав 5406 Н",
			SquareResistance: components.Parameter{Name: "Квадратное сопротивление",
				Unit: "Ом/кв", Value: 500.0},
			PermissibleSpecificPowerDissipation: components.Parameter{Name: "Допустимая удельная мощность рассеивания",
				Unit: "Вт/см^2", Value: 2.0},
			TemperatureCoefficientOfResistance: components.Parameter{Name: "ТКС", Symbol: "aR",
				Unit: "1/град * 10^-4", Value: 0.3},
			Senescence: components.Parameter{Name: "Необратимое относительное изменение сопротивления после 1000 ч работы под нагрузкой",
				Unit: "(1 Вт/см^2 при 85 °C), %", Value: 1},
		},
	}
}
